### ISSUE TITLE
Add Shortcake Support

### ISSUE THREAD

**Issue by robneu** [wedgies/wedgies-wordpress-plugin#2]
There's a new feature that's likely going to be included in WordPress in one of the next major versions which would allow you to have a visual representation of your shortcode directly in the WordPress editor. It also makes it easier for users to insert the shortcode via a UI.

Here's a [link](https://github.com/fusioneng/Shortcake) to the repo where the plugin is being built and prepped for inclusion in WordPress core. I think it'd make a nice enhancement, if you would like to support it.

**Comment by jimmyjacobson** [comment]
Thanks, Robert! We will take a look at this!

**Comment by jimmyjacobson** [comment]
We didn't end up adding Shortcake support for this, but the newest version of the Wedgies Wordpress Plugin does support visual previews now through our OEmbed endpoint!
