### ISSUE TITLE
Embed Preview in Admin Editor

### ISSUE THREAD

**Issue by robneu** [wedgies/wedgies-wordpress-plugin#3]
One final issue is that it would be nice to have the embed code work within the editor itself. Since WordPress 4.0 there has been a method available to preview embeds in the editor, but I haven't actually explored how it works yet.

I'm not sure if it would be possible to detect the embed handler from within the admin or if you'd just have to load your external js on every Tiny MCE instance, but it might be worth checking into.

**Comment by jimmyjacobson** [comment]
Great idea. I will leave this issue open while we look into it.

**Comment by jimmyjacobson** [comment]
It looks like Wedgies needs to be added to an internal Whitelist at Wordpress for this to work inside the editor.

http://codex.wordpress.org/Embeds

We can have our plugin add Wedgies.com to the whitelist for a site using this method:

http://codex.wordpress.org/Function_Reference/wp_oembed_add_provider

**Comment by slooker** [comment]
Sorry for the long delay!  This is fixed now.
